apiVersion: v1
kind: Secret
metadata: 
  name: oidc-authservice-client
  namespace: istio-system
type: Opaque
data:
  CLIENT_ID: YmYyOWE3M2UtY2M5Yy00MmY0LTg1NDctYzYwMmFmZGQ5ZmY1Cg==
  CLIENT_SECRET: <path:aaw-dev-cc-00-kv-argocd#kubeflow-client-secret>
