apiVersion: v1
kind: Secret
metadata: 
  name: super-duper-secret
  namespace: daaas-system
type: Opaque
data:
  CLIENT_ID: YmYyOWE3M2UtY2M5Yy00MmY0LTg1NDctYzYwMmFmZGQ5ZmY1
  CLIENT_SECRET: PHBhdGg6YWF3LWRldi1jYy0wMC1rdi1hcmdvY2Qja3ViZWZsb3ctY2xpZW50LXNlY3JldD4=
